### PR TITLE
[WIP] Document Cache Module

### LINKED ISSUE #29: Document Cache Module
I noticed that the cache module doesn't have documentation, opening this issue as a notification of intent

see #5 for more details

### PR DESCRIPTION
**Pull request by zacck**
## Description
Adding documentation stubs and doctests to the cache module, still very much a work in progress. 

## Motivation and Context
This provides documentation making features of the application accessible to developers 
Fixes #29 

## Types of changes

- [ ] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x ] Improvement/refactoring (non-breaking change that doesn't add any feature
  but make things better)

## Checklist
- [x] Check other PRs and make sure that the changes are not done yet.
- [x] The PR title is no longer than 64 characters.

### CODE REVIEW

**Comment by zacck** [comment]
@boydm wait I wasn't done

**Comment by boydm** [comment]
Sorry! It didn't break anything, so I was just on it

**Comment by zacck** [comment]
@boydm  actually your way is cooler let's do tiny PRs that way I can knock off functions instead of going for modules

**Comment by boydm** [comment]
Works for. Maybe not a PR for each individual function, but ones that make sense for whatever time you have. I just appreciate that you are helping out!

**Comment by zacck** [comment]
Will batch them as much as I can!

**Pull request merged**
