### PR TITLE
Fix Broken Scene Structure Link

### PR DESCRIPTION
**Pull request by derekbrown**
## Description

In the Getting Started, the `scene_structure` link was broken. It was linked to a file with an HTML extension, I changed to Markdown.

## Motivation and Context

Lots of new eyes on this cool project. Docs should work!

## Types of changes

- [x] Bug fix (a non-breaking change which fixes an issue)
- [ ] New feature (a non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to
  not work as expected)
- [x] Improvement/refactoring (non-breaking change that doesn't add any feature
  but make things better)

## Checklist

- [x] Check other PRs and make sure that the changes are not done yet.
- [x] The PR title is no longer than 64 characters.

### CODE REVIEW

**Comment by derekbrown** [comment]
That's fine if someone wants to tackle; but to be honest, I'm not that committed to going through the docs. I simply saw something and wanted to fix it.

**Comment by boydm** [comment]
Don't worry. I'll merge this and do the rest. In the middle of moving tho right now, so might take a few days...

**Comment by yordis** [comment]
@boydm @derekbrown @christhekeele did you verify that you didn't break `ex_doc` generated documentation?

Don't forget that anything under `guides` is being used by `mix docs` (ex_docs) so do not expect things to work as it would work in Github

**Comment by yordis** [comment]
The issue is simple, people forcing how Github works in that documentation section.

Folks should be aware that this is part of the ExDocs and maybe is more about the community habits, for myself, I do not check documentation in those `.md` anymore because I know that ExDoc is the tool used in the ecosystem for documentation.

About the code of conduct and contributing I will take a look, thanks a lot for the feedback

**Comment by boydm** [comment]
Travel day today. Will get on this soon

**Pull request merged**
